### PR TITLE
complete apiItem test

### PR DESCRIPTION
**Pull request by MaZelong**
complete apiItem test
created apiMessages tests but could not solve async errors
update apiItem at first
@dpastoor

### CODE REVIEW

**Comment by dpastoor** [comment]
@MaZelong it looks pretty good! If you can remove the 2 tests that have the isIn:true still in there and re-run to make sure the tests still pass we'll be good

**Comment by MaZelong** [comment]
@dpastoor do i make a new pull request ? i remove that and it works

**Comment by MaZelong** [comment]
@dpastoor i removed already and you can see it in the filed changed

**Comment by dpastoor** [comment]
great thanks

**Pull request merged**
